version: '3.3'

services:

  db:
    container_name: namo_db
    restart: always
    build: ./postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - WEBCONNEXION_PASSWORD=${WEBCONNEXION_PASSWORD}
    volumes: 
      - namo-database:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  web:
    container_name: namo_web
    build: ./apache
    depends_on:
      - db
    volumes: 
      - namo-web:/var/www/html
    restart: always
    ports:
      - ${APACHE_PORT}:80

volumes: 
  namo-database:
  namo-web: