version: '3.3'

services:

  db:
    container_name: postgres
    restart: always
    build: ./postgresql
    environment:
      - POSTGRES_USER=namo
      - POSTGRES_DB=namo
      - POSTGRES_PASSWORD=namo
    #volumes: 
    #  - postgres-data:/var/lib/postgresql/data
    ports:
      - 5431:5432

  web:
    container_name: apache
    build: ./apache
    #volumes: 
    #  - ../app:/usr/local/apache2/htdocs/
    ports:
      - 8081:80

#volumes: 
  #postgres-data:
  #webapp:
  #app: